import type { Lecture } from './types';

export const lecturesData: Lecture[] = [
    // LECTURE 1: Anatomy
    {
        id: 'l1',
        name: 'L1 Anatomy',
        mcqs: [
            { q: "1. Which of the following correctly describes the boundaries of the oral vestibule?", o: ["Anteriorly: Cheeks; Posteriorly: Palate", "Anteriorly: Lips; Laterally: Cheeks; Posteriorly and medially: Teeth and gums", "Superiorly: Hard palate; Inferiorly: Tongue", "Anteriorly: Gums; Posteriorly: Floor of the mouth", "Laterally: Lips; Medially: Floor of the mouth"], a: "b) Anteriorly: Lips; Laterally: Cheeks; Posteriorly and medially: Teeth and gums" },
            { q: "2. What is the superior boundary of the oral cavity proper?", o: ["Floor of the mouth", "Lips", "Palate", "Cheeks", "Anterior two-thirds of the tongue"], a: "c) Palate" },
            { q: "3. Which nerve is responsible for sensory innervation of the floor of the mouth?", o: ["Greater palatine nerve", "Nasopalatine nerve", "Buccal nerve", "Lingual nerve", "Facial nerve"], a: "d) Lingual nerve" },
            { q: "4. How long is the pharynx as described in the lecture?", o: ["3 inches", "4 inches", "5 inches", "6 inches", "7 inches"], a: "c) 5 inches" },
            { q: "5. The pharynx extends from the base of the skull to which vertebral level?", o: ["C4", "C5", "C6", "T1", "T2"], a: "c) C6" },
            { q: "6. Which feature is NOT associated with the nasopharynx?", o: ["Communication with nasal cavities via choanae", "Presence of the pharyngeal tonsil (adenoid)", "Contains the opening of the auditory tube", "Bounded inferiorly by the oropharyngeal isthmus at the level of the soft palate", "Direct communication with the laryngeal inlet"], a: "e) Direct communication with the laryngeal inlet" },
            { q: "7. What is the primary boundary between the oropharynx and the laryngopharynx?", o: ["The pharyngeal isthmus", "The level of the soft palate", "The upper border of the epiglottis", "The lower border of the cricoid cartilage", "The base of the skull"], a: "c) The upper border of the epiglottis" },
            { q: "8. Which of the following is a feature of the laryngopharynx?", o: ["Contains the pharyngeal tonsils", "Extends upward into the nasal cavity", "Features the piriform fossa on each lateral wall", "Has a wide superior opening into the nose", "Bounded laterally by the middle constrictor muscles only"], a: "c) Features the piriform fossa on each lateral wall" },
            { q: "9. What clinical significance is associated with the piriform fossa?", o: ["It serves as the primary location for saliva secretion", "It is the site for impaction of foreign bodies, which may damage the internal laryngeal nerve", "It is the main communication point between the oral cavity and pharynx", "It acts as the passage for the superior laryngeal artery", "It is the location where the pharyngeal tonsils reside"], a: "b) It is the site for impaction of foreign bodies, which may damage the internal laryngeal nerve" },
            { q: "10. The superior constrictor muscle of the pharynx originates from which structure?", o: ["Stylohyoid ligament", "Hyoid bone", "Thyroid cartilage", "Pterygo-mandibular ligament and its bony attachment", "Cricoid cartilage"], a: "d) Pterygo-mandibular ligament and its bony attachment" },
            { q: "11. Where do the fibers of the pharyngeal constrictor muscles insert?", o: ["On the base of the skull", "Into the fibrous median raphe extending between the pharyngeal tubercle and cricoid cartilage", "On the lateral walls of the pharynx", "On the inner surface of the thyroid cartilage", "Into the soft palate"], a: "b) Into the fibrous median raphe extending between the pharyngeal tubercle and cricoid cartilage" },
            { q: "12. Which structures are contained in the 1st pharyngeal gap?", o: ["Internal laryngeal nerve and superior laryngeal artery", "9th cranial nerve and stylopharyngeus muscle", "Tensor palati, levator palati muscles, Eustachian tube, and ascending palatine artery", "Recurrent laryngeal nerve and inferior laryngeal vessels", "Palatopharyngeus and salpingopharyngeus muscles"], a: "c) Tensor palati, levator palati muscles, Eustachian tube, and ascending palatine artery" },
            { q: "13. The 2nd pharyngeal gap contains which nerve-muscle pair?", o: ["Internal laryngeal nerve and superior laryngeal artery", "9th cranial nerve and the stylopharyngeus muscle", "Recurrent laryngeal nerve and inferior laryngeal vessels", "Glossopharyngeal nerve and palatopharyngeus muscle", "Vagus nerve and salpingopharyngeus muscle"], a: "b) 9th cranial nerve and the stylopharyngeus muscle" },
            { q: "14. Which structure is found in the 3rd pharyngeal gap?", o: ["Recurrent laryngeal nerve and inferior laryngeal vessels", "9th cranial nerve and stylopharyngeus muscle", "Internal laryngeal nerve and superior laryngeal artery", "Tensor palati muscle and Eustachian tube", "Lingual nerve and ascending palatine artery"], a: "c) Internal laryngeal nerve and superior laryngeal artery" },
            { q: "15. What structures pass through the 4th pharyngeal gap?", o: ["Glossopharyngeal nerve and ascending palatine artery", "Internal laryngeal nerve and superior laryngeal artery", "Recurrent laryngeal nerve and inferior laryngeal vessels", "Vagus nerve and pharyngeal branches of the sympathetic ganglion", "Tubal elevation and salpingopharyngeal fold"], a: "c) Recurrent laryngeal nerve and inferior laryngeal vessels" },
            { q: "16. Which of the following arteries contributes to the arterial supply of the pharynx?", o: ["Inferior thyroid artery only", "Left gastric artery exclusively", "Ascending pharyngeal, ascending palatine, and greater palatine arteries among others", "Bronchial artery solely", "Subclavian artery directly"], a: "c) Ascending pharyngeal, ascending palatine, and greater palatine arteries among others" },
            { q: "17. The pharyngeal plexus is formed by branches of which of the following?", o: ["Only the vagus nerve", "Only the glossopharyngeal nerve", "Pharyngeal branch of the vagus, glossopharyngeal nerve, and superior cervical sympathetic ganglion", "Mandibular branch of the trigeminal and the facial nerve", "Hypoglossal nerve and internal laryngeal nerve"], a: "c) Pharyngeal branch of the vagus, glossopharyngeal nerve, and superior cervical sympathetic ganglion" },
            { q: "18. Which clinical finding is associated with enlarged nasopharyngeal tonsils (adenoids) in children?", o: ["Excessive salivation", "Nasal obstruction with mouth breathing and protrusion of the tongue", "Sudden loss of taste", "Difficulty in mastication", "Deviation of the uvula"], a: "b) Nasal obstruction with mouth breathing and protrusion of the tongue" },
            { q: "19. Which esophageal constriction is located at the junction with the stomach?", o: ["6 inches from the incisor", "9 inches from the incisor", "12 inches from the incisor", "15 inches from the incisor", "At the level of T10 vertebra"], a: "d) 15 inches from the incisor" },
            { q: "20. What is the clinical significance of the close relationship between the esophagus and the left atrium?", o: ["It allows assessment of the left atrium's size by a barium swallow", "It facilitates direct endoscopic access to the heart", "It enhances arterial blood supply to both structures", "It prevents reflux of gastric contents", "It minimizes the risk of esophageal carcinoma"], a: "a) It allows assessment of the left atrium's size by a barium swallow" }
        ],
        written: [
          {
            q: "1. Discuss the structural differences between the oral vestibule and the oral cavity proper.",
            a: "<strong>Oral Vestibule:</strong> The <strong>oral vestibule</strong> is a slit‑like space bounded externally by the lips and cheeks and internally by the teeth and gums. It allows food manipulation and contains the openings of the parotid duct.<br><strong>Oral Cavity Proper:</strong> The <strong>oral cavity proper</strong> lies within the alveolar arches, roofed by the hard and soft palate, and floored by the anterior two‑thirds of the tongue and its mucosal reflections. It serves as the initial site of digestion, speech articulation, and taste."
          },
          {
            q: "2. Explain the clinical importance of the piriform fossa within the laryngopharynx.",
            a: "<strong>Piriform Fossa:</strong><br><em>Site of Impaction:</em> Common trap for fish bones and small foreign bodies, which can perforate the mucosa or migrate into surrounding tissues.<br><em>Nerve Risk:</em> Impaction or inflammation can injure the <em>internal laryngeal nerve</em>, causing anesthesia of the supraglottic mucosa and loss of cough reflex on that side.<br><em>Infection Potential:</em> Accumulated debris may lead to abscess formation, requiring prompt otolaryngologic evaluation."
          },
          {
            q: "3. Outline the contents of each of the four pharyngeal gaps and explain their significance.",
            a: "<strong>1st Gap (above Superior Constrictor):</strong> <em>Levator veli palatini</em>, <em>tensor veli palatini</em>, <em>auditory (Eustachian) tube</em>, <em>ascending palatine artery</em>.<br><strong>2nd Gap (between Superior & Middle Constrictors):</strong> <em>Stylopharyngeus muscle</em>, <em>glossopharyngeal nerve (CN IX)</em>, <em>stylohyoid ligament</em>.<br><strong>3rd Gap (between Middle & Inferior Constrictors):</strong> <em>Internal laryngeal nerve</em>, <em>superior laryngeal artery & vein</em>.<br><strong>4th Gap (below Inferior Constrictor):</strong> <em>Recurrent laryngeal nerve</em>, <em>inferior laryngeal artery & vein</em>.<br><strong>Significance:</strong> These intervals permit passage of neurovascular structures critical for palate elevation, pharyngeal sensation, and laryngeal motor and sensory functions."
          },
          {
            q: "4. Describe the clinical implications of esophageal constrictions as mentioned in the lecture.",
            a: "<strong>Clinical Implications:</strong><br><em>Endoscopy Challenges:</em> Constrictions at C6 (pharyngoesophageal junction), T4 (aortic arch), T5 (left main bronchus), and T10 (esophageal hiatus) can impede esophagoscope advancement.<br><em>Foreign Body Lodgment:</em> Narrow points where coins, bones, or dentures commonly get stuck.<br><em>Pathology Sites:</em> Predilection sites for corrosive strictures and esophageal carcinoma formation due to stasis and mucosal injury."
          },
          {
            q: "5. Summarize the blood supply, venous drainage, and lymphatic drainage of the esophagus.",
            a: "<strong>Blood Supply:</strong><br><em>Upper third:</em> Inferior thyroid arteries.<br><em>Middle third:</em> Branches of the thoracic aorta and bronchial artery.<br><em>Lower third:</em> Branches of the left gastric artery.<br><strong>Venous Drainage:</strong><br><em>Upper third:</em> Inferior thyroid veins.<br><em>Middle third:</em> Azygos and hemiazygos veins.<br><em>Lower third:</em> Left gastric vein.<br><strong>Lymphatic Drainage:</strong><br><em>Upper third:</em> Lower deep cervical nodes.<br><em>Middle third:</em> Posterior mediastinal nodes.<br><em>Lower third:</em> Celiac lymph nodes."
          }
        ]
    },
    // LECTURE 2: Histology
    {
        id: 'l2',
        name: 'L2 Histology',
        mcqs: [
            { q: "1. Which of the following best describes the outer surface of the lip?", o: ["A thick non-keratinized stratified squamous epithelium with abundant mucosal glands", "A thin skin composed of an epidermis and dermis containing sweat glands, hair follicles, and sebaceous glands", "A keratinized stratified squamous layer with a dense collagen core", "A transitional epithelium with areas of adipose tissue", "A mucous membrane exclusively lined by stratified cuboidal cells"], a: "b) A thin skin composed of an epidermis and dermis containing sweat glands, hair follicles, and sebaceous glands" },
            { q: "2. The inner surface of the lip is lined by which type of epithelium?", o: ["Keratinized stratified squamous epithelium", "Simple columnar epithelium", "Non-keratinized stratified squamous epithelium", "Transitional epithelium", "Pseudostratified ciliated columnar epithelium"], a: "c) Non-keratinized stratified squamous epithelium" },
            { q: "3. The vermilion zone of the lip is best characterized by:", o: ["A region with abundant sweat and sebaceous glands", "A transitional zone with thin, keratinized stratified squamous epithelium and no labial salivary or sweat glands", "An area composed entirely of mucous membrane with deep rugae", "A thick dermal layer with numerous hair follicles", "A zone with dense adipose tissue separating the skin and mucosa"], a: "b) A transitional zone with thin, keratinized stratified squamous epithelium and no labial salivary or sweat glands" },
            { q: "4. Which statement correctly explains the core of the lip?", o: ["It is composed solely of adipose tissue without significant vasculature", "It consists of dense connective tissue enriched with sensory nerves and capillaries", "It is made up of hyaline cartilage providing structural support", "It contains layers of skeletal muscle with a thick keratin layer", "It is primarily a continuation of the epidermal layer into the lip margin"], a: "b) It consists of dense connective tissue enriched with sensory nerves and capillaries" },
            { q: "5. The mucosa covering the tongue is primarily made up of which components?", o: ["Simple squamous epithelium with loose connective tissue", "Stratified squamous epithelium and a lamina propria containing dense collagen and minor salivary glands", "Pseudostratified columnar epithelium with cilia", "Simple columnar epithelium with abundant goblet cells", "Transitional epithelium with an underlying muscular layer"], a: "b) Stratified squamous epithelium and a lamina propria containing dense collagen and minor salivary glands" },
            { q: "6. Which type of lingual papilla is the most numerous on the dorsal surface of the anterior two-thirds of the tongue?", o: ["Fungiform papillae", "Filiform papillae", "Foliate papillae", "Circumvallate papillae", "Retrovallate papillae"], a: "b) Filiform papillae" },
            { q: "7. The primary function of the filiform papillae is to:", o: ["Facilitate taste via numerous taste buds", "Provide a rough surface to aid in the movement and manipulation of food during chewing", "Secrete serous fluid to enhance taste reception", "Protect the tongue by forming a barrier against pathogens", "Absorb nutrients from food particles"], a: "b) Provide a rough surface to aid in the movement and manipulation of food during chewing" },
            { q: "8. Fungiform papillae on the tongue are best described as having which features?", o: ["They are the most numerous papillae with a heavily keratinized epithelium and absence of taste buds", "They are elongated and conical with no taste buds", "They are mushroom-shaped, possess a non-keratinized epithelium, and contain a few taste buds", "They are large, encircled by a deep cleft, and contain the majority of taste buds", "They are exclusively found on the posterior third of the tongue"], a: "c) They are mushroom-shaped, possess a non-keratinized epithelium, and contain a few taste buds" },
            { q: "9. Foliate papillae are recognized by all of the following EXCEPT:", o: ["Their large size (1–3 mm)", "Being the least common type on the tongue", "Their broad shape encircled by a cleft (moat-like)", "Containing numerous taste buds", "Being the most densely distributed papillae on the tongue"], a: "e) Being the most densely distributed papillae on the tongue" },
            { q: "10. Which papilla type is closely associated with the von Ebner glands?", o: ["Filiform papillae", "Fungiform papillae", "Circumvallate papillae", "Foliate papillae", "All of the above"], a: "c) Circumvallate papillae" },
            { q: "11. Taste buds are primarily found in which locations on the tongue?", o: ["Embedded in the filiform papillae", "Concentrated on the lateral surfaces of the circumvallate papillae", "Evenly distributed over both dorsal and ventral surfaces", "Exclusively in the fungiform papillae", "Located in the smooth epithelium of the posterior third"], a: "b) Concentrated on the lateral surfaces of the circumvallate papillae" },
            { q: "12. The structure of a taste bud consists of all the following cell types EXCEPT:", o: ["Tall columnar gustatory (taste) cells", "Supporting cells", "Basal cells responsible for cell turnover", "Keratinized squamous cells", "Cells with microvilli projecting towards a taste pore"], a: "d) Keratinized squamous cells" },
            { q: "13. The posterior third of the tongue is distinct in that it:", o: ["Exhibits hundreds of lingual papillae", "Contains lingual tonsils with a smooth stratified squamous epithelium and no papillae", "Has a heavily keratinized dorsal epithelium with prominent filiform papillae", "Lacks any associated lymphoid tissue", "Is lined by non-keratinized cuboidal epithelium with numerous taste buds"], a: "b) Contains lingual tonsils with a smooth stratified squamous epithelium and no papillae" },
            { q: "14. Which salivary gland is characterized as a pure serous gland with a thick fibrous capsule containing fat cells?", o: ["Parotid gland", "Submandibular gland", "Sublingual gland", "Minor salivary glands", "Mixed seromucous glands"], a: "a) Parotid gland" },
            { q: "15. Serous acini in the salivary glands are recognized by all the following features EXCEPT:", o: ["Pyramidal cell shape with deep basophilic cytoplasm", "Well-developed rough endoplasmic reticulum and Golgi apparatus", "Central and rounded nuclei", "Presence of apical electron-lucent mucous granules", "Surrounding myoepithelial (basket) cells"], a: "d) Presence of apical electron-lucent mucous granules" },
            { q: "16. Mucous acini in salivary glands primarily secrete:", o: ["Digestive enzymes such as amylase", "Hydrophilic mucins that facilitate lubrication", "Proline-rich proteins with antimicrobial properties", "Ion-transporting proteins", "Serous secretions rich in lysozyme"], a: "b) Hydrophilic mucins that facilitate lubrication" },
            { q: "17. Mixed (seromucous) acini are characterized by:", o: ["A predominance of serous cells with no mucous component", "A predominance of mucous cells along with serous demilune (crescent) formations", "A completely balanced mixture of serous and mucous cells", "Lack of surrounding myoepithelial cells", "Cells that are incapable of secreting either mucin or enzymes"], a: "b) A predominance of mucous cells along with serous demilune (crescent) formations" },
            { q: "18. What is the primary function of myoepithelial (basket) cells in salivary glands?", o: ["They produce and store mucins", "They form the ductal lining of the gland", "They contract to help expel secretions from the acini", "They are responsible for the synthesis of α-amylase", "They serve as structural support without any contractile function"], a: "c) They contract to help expel secretions from the acini" },
            { q: "19. The striated ducts in salivary glands function to:", o: ["Secrete digestive enzymes directly", "Reabsorb sodium ions from the acinar secretions, rendering the saliva hypotonic", "Simply convey saliva without modification", "Provide a passage exclusively for mucous secretions", "Store secretions until needed"], a: "b) Reabsorb sodium ions from the acinar secretions, rendering the saliva hypotonic" },
            { q: "20. Which of the following best describes the duct system in salivary glands?", o: ["It consists of one uniform duct type lined solely by stratified squamous epithelium", "It includes intercalated ducts, striated ducts, interlobular ducts, interlobar ducts, and a main duct with varying epithelial linings opening into the mouth", "It is made up exclusively of intercalated ducts that secrete enzymes", "It lacks any structural division by fibrous septa", "It only contains ducts lined by non-keratinized cuboidal epithelium"], a: "b) It includes intercalated ducts, striated ducts, interlobular ducts, interlobar ducts, and a main duct with varying epithelial linings opening into the mouth" }
        ],
        written: [
          {
            q: "1. Discuss the differences in epithelial lining between the outer surface, the inner mucosal surface, and the vermilion zone of the lip.",
            a: "<strong>Outer Surface:</strong><br><em>Skin:</em> Thin keratinized epithelium with epidermis/dermis, containing sweat glands, hair follicles, and sebaceous glands; protects against environmental trauma.<br><strong>Inner Mucosal Surface:</strong><br><em>Epithelium:</em> Thick, non‑keratinized stratified squamous with lamina propria rich in minor salivary glands; keeps mucosa moist and resilient.<br><strong>Vermilion Zone:</strong><br><em>Transitional Epithelium:</em> Very thin keratinized stratified squamous lacking glands, overlying dense capillary network—gives characteristic red color and high tactile sensitivity."
          },
          {
            q: "2. Explain the functional roles of the different types of lingual papillae.",
            a: "<strong>Filiform Papillae:</strong> Most numerous, conical and keratinized; provide friction to manipulate food.<br><strong>Fungiform Papillae:</strong> Mushroom‑shaped, less keratinized, scattered taste buds; detect sweet and umami.<br><strong>Foliate Papillae:</strong> Leaf‑shaped lateral folds with deep clefts; numerous taste buds sensitive to sour.<br><strong>Circumvallate Papillae:</strong> Large, dome‑shaped row anterior to sulcus terminalis, associated with von Ebner glands; important for bitter taste detection."
          },
          {
            q: "3. Describe the structure and turnover process of taste buds.",
            a: "<strong>Structure:</strong><br><em>Cell Types:</em> Gustatory (sensory) cells with apical microvilli projecting into taste pore; supporting cells; basal (stem) cells.<br><strong>Turnover:</strong><br><em>Renewal:</em> Basal cells proliferate and differentiate; entire taste bud renews every 7–10 days, essential for maintaining taste acuity and recovery after injury."
          },
          {
            q: "4. Compare and contrast the parotid, submandibular, and sublingual salivary glands in terms of their histological features and secretory functions.",
            a: "<strong>Parotid Gland:</strong><br><em>Histology:</em> Pure serous acini, thick capsule, prominent interlobar fat; secretes watery, enzyme‑rich saliva (α‑amylase).<br><strong>Submandibular Gland:</strong><br><em>Histology:</em> Mixed serous and mucous acini (predominantly serous), moderate capsule with fat; produces both enzymes and mucins for lubrication.<br><strong>Sublingual Gland:</strong><br><em>Histology:</em> Mostly mucous acini, thin capsule, few serous demilunes; secretes viscous mucin‑rich saliva for mucosal protection."
          },
          {
            q: "5. Outline the organization of the duct system in salivary glands, focusing on the roles of intercalated and striated ducts.",
            a: "<strong>Intercalated Ducts:</strong><br><em>Lining:</em> Simple cuboidal cells directly from acini; conduct primary saliva.<br><em>Role:</em> Minor modification—secrete bicarbonate, absorb some Cl⁻.<br><strong>Striated Ducts:</strong><br><em>Lining:</em> High columnar cells with basal mitochondrial striations; large surface area.<br><em>Role:</em> Reabsorb Na⁺, secrete K⁺—produce hypotonic saliva.<br><strong>Excretory Ducts:</strong><br><em>Pathway:</em> Interlobular → interlobar → main duct; epithelium transitions to stratified columnar/squamous before oral opening."
          }
        ]
    },
    // LECTURE 3: Anatomy
    {
        id: 'l3',
        name: 'L3 Anatomy',
        mcqs: [
            { q: "1. Which of the following best describes the overall shape of the parotid gland?", o: ["Oval", "Triangular", "Inverted pyramid", "Rectangular", "Circular"], a: "c) Inverted pyramid" },
            { q: "2. The parotid gland is enclosed by a capsule derived from which anatomical structure?", o: ["Superficial fascia of the face", "Deep cervical fascia (investing layer)", "Platysma fascia", "Mandibular periosteum", "Buccopharyngeal fascia"], a: "b) Deep cervical fascia (investing layer)" },
            { q: "3. Which ligament separates the parotid gland from the submandibular gland?", o: ["Stylomandibular ligament", "Sphenomandibular ligament", "Hyoid ligament", "Zygomatic ligament", "Masseteric ligament"], a: "a) Stylomandibular ligament" },
            { q: "4. Which nerve provides the parasympathetic (secretomotor) innervation to the parotid gland?", o: ["Facial nerve via the chorda tympani", "Glossopharyngeal nerve via the lesser petrosal nerve and otic ganglion", "Trigeminal nerve via the auriculotemporal branch", "Vagus nerve directly", "Hypoglossal nerve"], a: "b) Glossopharyngeal nerve via the lesser petrosal nerve and otic ganglion" },
            { q: "5. What is the correct order of structures, from superficial to deep, found within the parotid gland?", o: ["External carotid artery, facial nerve, posterior facial vein", "Facial nerve, external carotid artery, posterior facial vein", "Posterior facial vein, facial nerve, external carotid artery", "Facial nerve, posterior facial vein, external carotid artery", "External carotid artery, posterior facial vein, facial nerve"], a: "d) Facial nerve, posterior facial vein, external carotid artery" },
            { q: "6. Which of the following structures is related to the superior end (base) of the parotid gland?", o: ["Cervical branch of the facial nerve", "Mastoid process", "External auditory meatus", "Buccinator muscle", "Submandibular duct"], a: "c) External auditory meatus" },
            { q: "7. The lateral (superficial) surface of the parotid gland is closely associated with which of the following?", o: ["Medial pterygoid muscle", "Superficial temporal vessels and auriculo-temporal nerve", "Mandibular branch of the facial nerve", "Posterior belly of the digastric muscle", "Great auricular nerve and superficial parotid lymph nodes"], a: "e) Great auricular nerve and superficial parotid lymph nodes" },
            { q: "8. The \"bone sandwich\" relation of the anteromedial surface of the parotid gland includes which muscle?", o: ["Sternomastoid", "Lateral pterygoid", "Masseter", "Digastric", "Temporalis"], a: "c) Masseter" },
            { q: "9. The parotid duct (Stensen's duct) is approximately 5 cm long and passes over which muscle?", o: ["Temporalis", "Masseter", "Sternomastoid", "Medial pterygoid", "Buccinator"], a: "b) Masseter" },
            { q: "10. In its course, the parotid duct pierces through several structures. Which of the following is the correct sequence?", o: ["Buccal mucosa → buccinator muscle → buccopharyngeal fascia", "Masseter → buccal pad of fat → buccinator muscle", "Masseter → buccal pad of fat → buccopharyngeal fascia → buccinator muscle", "Buccinator muscle → masseter → buccal mucosa", "Buccopharyngeal fascia → masseter → buccal pad of fat"], a: "c) Masseter → buccal pad of fat → buccopharyngeal fascia → buccinator muscle" },
            { q: "11. Which of the following nerves supplies the sensory fibers to the parotid gland's parenchyma?", o: ["Great auricular nerve", "Auriculotemporal nerve", "Lingual nerve", "Facial nerve", "Hypoglossal nerve"], a: "b) Auriculotemporal nerve" },
            { q: "12. The submandibular gland is divided by the mylohyoid muscle into which two parts?", o: ["Medial and lateral parts", "Superior and inferior parts", "Deep and superficial parts", "Anterior and posterior parts", "Central and peripheral parts"], a: "c) Deep and superficial parts" },
            { q: "13. Wharton's duct (the submandibular duct) opens in the oral cavity at the side of which structure?", o: ["Frenulum labii superioris", "Sublingual papilla at the side of the frenulum linguae", "Base of the tongue", "Lateral floor of the mouth", "Buccal mucosa"], a: "b) Sublingual papilla at the side of the frenulum linguae" },
            { q: "14. During its course, Wharton's duct is positioned between which pair of nerves?", o: ["Lingual nerve and hypoglossal nerve", "Auriculotemporal nerve and great auricular nerve", "Chorda tympani and glossopharyngeal nerve", "Inferior alveolar nerve and lingual nerve", "Facial nerve and trigeminal nerve"], a: "a) Lingual nerve and hypoglossal nerve" },
            { q: "15. The parasympathetic (secretomotor) supply to the submandibular and sublingual glands is provided by which pathway?", o: ["Inferior salivatory nucleus → glossopharyngeal nerve", "Superior salivatory nucleus → facial nerve's chorda tympani → submandibular ganglion", "Direct fibers from the trigeminal nerve", "Vagus nerve through its recurrent laryngeal branch", "Hypoglossal nerve via motor fibers"], a: "b) Superior salivatory nucleus → facial nerve's chorda tympani → submandibular ganglion" },
            { q: "16. Which sympathetic fibers supply the parotid gland?", o: ["Fibers from the otic ganglion", "Fibers running along the posterior facial vein", "Fibers from the plexus around the external carotid artery", "Direct branches from the internal carotid plexus", "Fibers within the mandibular nerve"], a: "c) Fibers from the plexus around the external carotid artery" },
            { q: "17. In the relations of the sublingual gland, which structure is found medially?", o: ["Sublingual fossa", "Mylohyoid muscle", "Genioglossus muscle, lingual nerve, and submandibular duct", "Buccinator muscle", "Masseter muscle"], a: "c) Genioglossus muscle, lingual nerve, and submandibular duct" },
            { q: "18. The small ducts of the sublingual gland typically open directly into the floor of the mouth or join which other duct?", o: ["Parotid duct", "Accessory submandibular duct", "Wharton's duct", "Stenson's duct", "Lingual duct"], a: "c) Wharton's duct" },
            { q: "19. Which of the following is NOT a relation of the posteromedial surface of the parotid gland?", o: ["Mastoid process", "Sternomastoid muscle", "Posterior belly of the digastric muscle", "Auriculo-temporal nerve pierces the gland", "Masseter muscle"], a: "e) Masseter muscle" },
            { q: "20. In the \"In Class Exercise\" scenario, a 50-year-old male is diagnosed with a parotid gland tumor. Which muscle is related to the anteromedial surface of the parotid gland as indicated in the lecture?", o: ["Lateral pterygoid", "Mylohyoid", "Temporalis", "Sternomastoid", "Masseter"], a: "e) Masseter" }
        ],
        written: [
          {
            q: "1. Describe the course of the parotid duct (Stensen’s duct) from its origin to its opening in the oral cavity.",
            a: "<strong>Origin:</strong> Emerging from the anterior border of parotid gland.<br><strong>Course:</strong> Runs ~5 cm horizontally over masseter, turns medially, pierces buccal fat pad, buccopharyngeal fascia, and buccinator muscle.<br><strong>Opening:</strong> East of second maxillary molar into the vestibule; palpable landmark in sialolithiasis."
          },
          {
            q: "2. Explain the nerve pathway responsible for providing parasympathetic (secretomotor) innervation to the parotid gland.",
            a: "<strong>Origin:</strong> Inferior salivatory nucleus (glossopharyngeal nerve CN IX).<br><strong>Pathway:</strong> Tympanic branch → tympanic plexus → lesser petrosal nerve → otic ganglion (synapse) → postsynaptic fibers via auriculotemporal nerve (V3) to gland."
          },
          {
            q: "3. List the anatomical relations of the lateral (superficial) surface of the parotid gland.",
            a: "<strong>Superficial Relations:</strong><br>– Skin and superficial fascia<br>– Platysma muscle fibers<br>– Great auricular nerve branches<br>– Superficial parotid (preauricular) lymph nodes"
          },
          {
            q: "4. How is the submandibular gland anatomically divided, and what is the significance of the mylohyoid muscle in this division?",
            a: "<strong>Division:</strong> Superficial part wraps around posterior border of mylohyoid; deep part lies in sublingual space above mylohyoid.<br><strong>Mylohyoid:</strong> Forms muscular diaphragm of floor of mouth; separates superficial and deep lobes."
          },
          {
            q: "5. Identify the key structures involved in the parasympathetic innervation of the submandibular and sublingual glands and describe their pathway briefly.",
            a: "<strong>Origin:</strong> Superior salivatory nucleus (facial nerve CN VII).<br><strong>Pathway:</strong> Chorda tympani → joins lingual nerve (V3) → synapse in submandibular ganglion → postganglionic fibers to both glands."
          }
        ]
    },
     // LECTURE 4: Physiology
    {
         id: 'l4',
         name: 'L4 Physiology',
         mcqs: [
             { q: "1. A 30-year-old woman presents with dry mouth and mild submandibular swelling after meals. Which salivary gland is primarily responsible for producing \"mixed\" saliva?", o: ["Parotid gland", "Sublingual gland", "Submandibular gland", "Minor salivary glands", "Palatine gland"], a: "c) Submandibular gland" },
             { q: "2. Where are gastrin-producing G cells predominantly located?", o: ["In the ileum", "In the pancreatic islets", "In the gastric mucosa of the antrum", "In the duodenum", "In the large intestine"], a: "c) In the gastric mucosa of the antrum" },
             { q: "3. A patient begins to salivate upon merely smelling food. This anticipatory increase in salivation is an example of which type of reflex?", o: ["Unconditioned reflex", "Conditioned reflex", "Involuntary reflex", "Gastrocolic reflex", "Oesophago‐salivary reflex"], a: "b) Conditioned reflex" },
             { q: "4. Secretin's primary action in digestion is to:", o: ["Enhance nutrient absorption by the intestines", "Stimulate enzyme secretion from the exocrine pancreas", "Stimulate bicarbonate secretion from the pancreas", "Inhibit gastric acid secretion", "Increase bile production in the liver"], a: "c) Stimulate bicarbonate secretion from the pancreas" },
             { q: "5. According to the lecture, which hormone is included in the secretin family?", o: ["Glucagon", "Insulin", "GIP", "Cortisol", "Aldosterone"], a: "c) GIP" },
             { q: "6. The vago‐vagal reflex plays a crucial role in the regulation of gastrointestinal secretions. Which statement best describes this reflex?", o: ["It involves only efferent parasympathetic signals to stimulate secretions.", "It integrates both afferent sensory and efferent parasympathetic signals to regulate gut functions.", "It is responsible solely for the inhibitory regulation of digestive enzymes.", "It is mediated by the sympathetic nervous system.", "It is activated exclusively during the gastric phase of digestion."], a: "b) It integrates both afferent sensory and efferent parasympathetic signals to regulate gut functions." },
             { q: "7. Which of the following correctly matches the salivary gland with its predominant secretion type?", o: ["Parotid gland - mixed seromucous saliva", "Submandibular gland - serous saliva only", "Sublingual gland - mucin-rich saliva", "Minor salivary glands - watery enzyme-rich saliva", "Parotid gland - mucin secretion"], a: "c) Sublingual gland - mucin-rich saliva" },
             { q: "8. During which phase of salivary secretion are sensory stimuli (such as the sight or smell of food) most influential?", o: ["Gastric phase", "Intestinal phase", "Cephalic (anticipatory) phase", "Postprandial phase", "Resting phase"], a: "c) Cephalic (anticipatory) phase" },
             { q: "9. Which neural pathway is primarily responsible for parasympathetic stimulation of the parotid gland?", o: ["Facial nerve via the chorda tympani", "Glossopharyngeal nerve via the tympanic and lesser petrosal nerves and the otic ganglion", "Vagus nerve via the dorsal motor nucleus", "Trigeminal nerve via its mandibular division", "Hypoglossal nerve via its motor fibers"], a: "b) Glossopharyngeal nerve via the tympanic and lesser petrosal nerves and the otic ganglion" },
             { q: "10. Which neural ganglion transmits parasympathetic signals to the submandibular and sublingual glands?", o: ["Pterygopalatine ganglion", "Otic ganglion", "Submandibular ganglion", "Ciliary ganglion", "Superior cervical ganglion"], a: "c) Submandibular ganglion" },
             { q: "11. Which component of saliva is primarily responsible for its lubricating properties?", o: ["Amylase", "Mucin", "Lactoferrin", "Proline-rich proteins", "Electrolytes"], a: "b) Mucin" },
             { q: "12. Lactoferrin in saliva is best known for its:", o: ["Enzymatic breakdown of carbohydrates", "Role in taste perception", "Antimicrobial and iron-binding properties", "Function in pH regulation", "Stimulation of bicarbonate secretion"], a: "c) Antimicrobial and iron-binding properties" },
             { q: "13. Which of the following best differentiates unconditioned from conditioned salivary responses?", o: ["Unconditioned responses require prior learning, whereas conditioned responses are innate.", "Conditioned responses are learned associations, while unconditioned responses are innate reactions to stimuli.", "Both responses are learned through repeated exposure.", "Unconditioned responses involve the sympathetic system, and conditioned responses involve the parasympathetic system.", "Conditioned responses occur only after ingestion of food, unlike unconditioned responses."], a: "b) Conditioned responses are learned associations, while unconditioned responses are innate reactions to stimuli." },
             { q: "14. Which of the following is most likely to stimulate salivary secretion during the cephalic phase?", o: ["The mechanical presence of food in the stomach", "The taste of food in the oral cavity", "Olfactory and visual stimuli related to food", "Chemical irritation of the intestinal mucosa", "Distension of the colon"], a: "c) Olfactory and visual stimuli related to food" },
             { q: "15. In the context of the gastrointestinal reflex regulation demonstrated in the lecture, which of the following does NOT significantly affect salivary secretion?", o: ["Anticipatory sensory cues", "Mechanical stimulation of the oral mucosa", "Vagal afferent signals", "Sympathetic stimulation from stress", "Conditioned reflexes"], a: "d) Sympathetic stimulation from stress" },
             { q: "16. Which gland's secretions are most enriched in enzymes compared to mucins?", o: ["Sublingual gland", "Submandibular gland", "Minor salivary glands", "Parotid gland", "Palatal gland"], a: "d) Parotid gland" },
             { q: "17. What is the principal functional significance of the vago‐vagal reflex in gastrointestinal regulation?", o: ["It only regulates gastric motility, not secretion.", "It coordinates sensory input and parasympathetic output for both digestive enzyme and salivary secretion control.", "It solely mediates inhibitory control over bile secretion.", "It primarily triggers sympathetic responses.", "It is restricted to regulating intestinal absorption."], a: "b) It coordinates sensory input and parasympathetic output for both digestive enzyme and salivary secretion control." },
             { q: "18. Which of the following accurately reflects the role of conditioned reflexes in salivary secretion?", o: ["They diminish salivary output when food is anticipated.", "They are triggered exclusively by gastric distension.", "They enhance secretion in response to learned sensory cues such as sight and smell of food.", "They require direct stimulation of the oral mucosa.", "They are dependent on circulating hormone levels only."], a: "c) They enhance secretion in response to learned sensory cues such as sight and smell of food." },
             { q: "19. Which statement best describes the comparative composition of saliva from different glands?", o: ["All salivary glands secrete identical fluids regardless of anatomical location.", "The parotid gland produces a predominantly mucinous secretion, while the submandibular gland produces only serous fluid.", "The submandibular gland secretes mixed (seromucous) saliva, the parotid predominantly serous, and the sublingual predominantly mucinous saliva.", "Minor salivary glands produce enzyme-rich secretions, whereas the parotid produces mucus.", "The sublingual gland is the sole producer of digestive enzymes."], a: "c) The submandibular gland secretes mixed (seromucous) saliva, the parotid predominantly serous, and the sublingual predominantly mucinous saliva." },
             { q: "20. Based on the lecture, which factor is most critical for initiating salivary secretion during meal anticipation?", o: ["Gastric acid secretion", "Mechanical distension of the stomach", "Conditioned sensory stimuli that activate the cephalic phase", "Elevated blood levels of secretin", "Sympathetic nervous stimulation"], a: "c) Conditioned sensory stimuli that activate the cephalic phase" }
         ],
         written: [
          {
            q: "1. Describe the three phases of salivary secretion and identify the primary stimulus for each phase.",
            a: "<strong>Cephalic Phase:</strong><br><em>Stimulus:</em> Sight, smell, thought of food activate cortical centers → vagal outflow.<br><strong>Oral (Masticatory/Gustatory) Phase:</strong><br><em>Stimulus:</em> Mechanical chewing and taste receptor activation in mouth.<br><strong>Gastric Phase:</strong><br><em>Stimulus:</em> Stomach distension and chemical presence of food (vago‑vagal feedback); minor contribution to saliva."
          },
          {
            q: "2. Explain the role of the vago‐vagal reflex in the regulation of gastrointestinal functions, specifically in salivary secretion.",
            a: "<strong>Vago‑Vagal Reflex:</strong><br><em>Afferent (Sensory):</em> Stretch and chemoreceptors in gut send signals via vagus to dorsal vagal complex.<br><em>Efferent (Parasympathetic):</em> Vagal motor fibers modulate gastric and salivary secretions.<br><em>Effect:</em> Enhances enzyme and fluid secretion to prepare both saliva and gastric juices for digestion."
          },
          {
            q: "3. Discuss the neural pathways that mediate the parasympathetic stimulation of the parotid gland versus the submandibular/sublingual glands.",
            a: "<strong>Parotid:</strong><br><em>CN IX Pathway:</em> Inferior salivatory nucleus → tympanic nerve → lesser petrosal → otic ganglion → auriculotemporal nerve.<br><strong>Submandibular/Sublingual:</strong><br><em>CN VII Pathway:</em> Superior salivatory nucleus → chorda tympani → lingual nerve → submandibular ganglion → glands."
          },
          {
            q: "4. Compare the composition of saliva secreted by the parotid, submandibular, and sublingual glands, and explain the functional significance of these differences.",
            a: "<strong>Parotid:</strong><br><em>Type:</em> Serous, enzyme‑rich (α‑amylase) for starch breakdown.<br><strong>Submandibular:</strong><br><em>Type:</em> Mixed seromucous—balances lubrication and digestion.<br><strong>Sublingual:</strong><br><em>Type:</em> Mucin‑rich—provides mucosal protection and lubrication."
          },
          {
            q: "5. Analyze how conditioned reflexes contribute to the regulation of salivary secretion and overall digestive preparation.",
            a: "<strong>Conditioned Reflexes:</strong><br><em>Mechanism:</em> Learned associations (e.g., Pavlov’s dogs) between sensory cues and food.<br><em>Outcome:</em> Early salivary response primes oral cavity and gastrointestinal tract for incoming food, optimizing digestion."
          }
        ]
    },
     // LECTURE 5: Biochemistry
    {
         id: 'l5',
         name: 'L5 Biochemistry',
         mcqs: [
             { q: "1. Which of the following represents the primary end products of dietary carbohydrate digestion in the small intestine?", o: ["Disaccharides", "Oligosaccharides", "Monosaccharides (glucose, fructose, and galactose)", "Polysaccharides", "Dextrans"], a: "c) Monosaccharides (glucose, fructose, and galactose)" },
             { q: "2. In the oral cavity, which enzyme initiates the digestion of starch by cleaving α1→4 glycosidic bonds?", o: ["Pancreatic amylase", "Gastric lipase", "Salivary amylase", "Intestinal disaccharidase", "Lingual lipase"], a: "c) Salivary amylase" },
             { q: "3. Why is the activity of salivary amylase abruptly reduced in the stomach?", o: ["It is denatured by bile salts", "Pancreatic enzymes inhibit it", "Gastric HCl lowers the pH", "It is bound by intestinal proteins", "It is inactivated by mechanical churning"], a: "c) Gastric HCl lowers the pH" },
             { q: "4. Which enzyme is responsible for the completion of starch digestion in the small intestine?", o: ["Gastric amylase", "Lingual lipase", "Pancreatic amylase", "Lactase", "Maltase"], a: "c) Pancreatic amylase" },
             { q: "5. Once disaccharides are formed in the small intestine, what is the role of intestinal disaccharidases?", o: ["They convert oligosaccharides to polysaccharides", "They hydrolyze disaccharides to monosaccharides", "They transport monosaccharides into the enterocytes", "They inactivate pancreatic amylase", "They bind dietary fiber"], a: "b) They hydrolyze disaccharides to monosaccharides" },
             { q: "6. Glucose and galactose are absorbed in the small intestine primarily via which of the following mechanisms?", o: ["Simple diffusion", "Facilitated diffusion via GLUT5", "Active transport by SGLUT-1", "Endocytosis", "Osmotic transport"], a: "c) Active transport by SGLUT-1" },
             { q: "7. At the basal membrane of enterocytes, which transporter facilitates the movement of sugars into the bloodstream?", o: ["SGLUT-1", "GLUT-2", "GLUT-5", "Na+-K+ ATPase pump", "SGLUT-2"], a: "b) GLUT-2" },
             { q: "8. How are fructose and galactose handled after absorption from the small intestine?", o: ["They are absorbed directly into the systemic circulation", "They are excreted unchanged in the urine", "They are transported via the hepatic portal vein to the liver for conversion to glucose", "They are immediately stored as glycogen in muscle", "They pass unchanged through the kidneys"], a: "c) They are transported via the hepatic portal vein to the liver for conversion to glucose" },
             { q: "9. Which of the following pathways is a primary fate of absorbed glucose once it enters systemic circulation?", o: ["Direct storage as triglycerides only", "Conversion solely into amino acids", "Oxidation via glycolysis and the Krebs cycle", "Binding to plasma proteins", "Immediate excretion in bile"], a: "c) Oxidation via glycolysis and the Krebs cycle" },
             { q: "10. Which enzyme is the main catalyst for the digestion of dietary triglycerides in the small intestine?", o: ["Lingual lipase", "Gastric lipase", "Pancreatic lipase", "Bile salt-activated lipase", "Intestinal protease"], a: "c) Pancreatic lipase" },
             { q: "11. What are the principal digestion products of triglyceride hydrolysis by pancreatic lipase?", o: ["Triglycerides and phospholipids", "Monoglycerides, glycerol, and free fatty acids", "Diglycerides and cholesterol", "Fatty acids and bile acids", "Glycolipids"], a: "b) Monoglycerides, glycerol, and free fatty acids" },
             { q: "12. After pancreatic lipase acts on triglycerides, which enzyme further digests the monoglycerides?", o: ["Gastric amylase", "Pancreatic protease", "Intestinal lipase", "Chymotrypsin", "Peptidase"], a: "c) Intestinal lipase" },
             { q: "13. Which type of dietary lipid makes up approximately 99% of all dietary lipids?", o: ["Phospholipids", "Cholesterol esters", "Triglycerides", "Glycolipids", "Free fatty acids"], a: "c) Triglycerides" },
             { q: "14. Which function is NOT a primary role of dietary lipids?", o: ["Serving as a major energy source", "Supplying essential fatty acids and fat‐soluble vitamins", "Acting as the primary substrate for glycolysis", "Forming structural components of cell membranes", "Providing precursors for steroid synthesis"], a: "c) Acting as the primary substrate for glycolysis" },
             { q: "15. During protein digestion in the stomach, the acidic pH is critical for which of the following processes?", o: ["Emulsification of fats", "Activation of pepsinogen to pepsin and protein denaturation", "Hydrolysis of disaccharides", "Inhibition of pancreatic enzymes", "Formation of amino acid carrier proteins"], a: "b) Activation of pepsinogen to pepsin and protein denaturation" },
             { q: "16. Pepsin, an important proteolytic enzyme in the stomach, has an optimum activity at which pH range?", o: ["5.0–6.0", "7.0–8.0", "1.5–2.2", "3.5–4.0", "8.0–9.0"], a: "c) 1.5–2.2" },
             { q: "17. Which pancreatic enzymes are involved in the digestion of proteins in the small intestine?", o: ["Lactase and sucrase", "Amylase and lipase", "Trypsin, chymotrypsin, and carboxypeptidase", "Gastric lipase and intestinal lipase", "Pepsin and renin"], a: "c) Trypsin, chymotrypsin, and carboxypeptidase" },
             { q: "18. The final products of protein digestion that can be absorbed by the small intestine are:", o: ["Polypeptides", "Oligopeptides", "Amino acids", "Nucleotides", "Fatty acids"], a: "c) Amino acids" },
             { q: "19. What is the primary mechanism for amino acid absorption in the small intestine?", o: ["Passive diffusion through cell membranes", "Endocytosis via vesicular transport", "Active transport using carrier proteins", "Facilitated diffusion via GLUT transporters", "Paracellular transport through tight junctions"], a: "c) Active transport using carrier proteins" },
             { q: "20. In addition to the carrier protein system, the absorption of amino acids utilizes which alternative mechanism that involves glutathione?", o: ["Na+/K+ pump mechanism", "γ-Glutamyl cycle", "Urea cycle", "Krebs cycle", "Glycolytic pathway"], a: "b) γ-Glutamyl cycle" }
         ],
         written: [
          {
            q: "1. Describe the three main mechanisms by which monosaccharides are absorbed in the small intestine and provide an example of a sugar or condition that utilizes each mechanism.",
            a: "<strong>Simple Diffusion:</strong><br><em>Example:</em> Pentoses (ribose) diffuse down concentration gradients.<br><strong>Facilitated Diffusion:</strong><br><em>Example:</em> Fructose transported via GLUT5 on apical membrane and GLUT2 basolateral.<br><strong>Active Co‑transport:</strong><br><em>Example:</em> Glucose and galactose via SGLT‑1 (Na⁺‑dependent); electrogenic transport driven by Na⁺ gradient."
          },
          {
            q: "2. Explain the sequential roles of pancreatic lipase and intestinal lipase in the digestion of dietary triglycerides.",
            a: "<strong>Pancreatic Lipase:</strong><br><em>Action:</em> Hydrolyzes triglycerides at the 1 and 3 positions to yield 2‑monoglycerides and free fatty acids; colipase anchors enzyme to micelles.<br><strong>Intestinal (Brush Border) Lipase:</strong><br><em>Action:</em> Further cleaves monoglycerides → glycerol + fatty acids, facilitating uptake into enterocytes."
          },
          {
            q: "3. Discuss the role of gastric HCl in protein digestion and its effects on both the protein substrate and the zymogen pepsinogen.",
            a: "<strong>Protein Denaturation:</strong><br><em>Effect:</em> Unfolds tertiary structure, exposing peptide bonds.<br><strong>Pepsinogen Activation:</strong><br><em>Mechanism:</em> Low pH (1.5–2.2) converts pepsinogen → active pepsin, which cleaves peptide bonds near aromatic residues."
          },
          {
            q: "4. Compare the carrier protein transport system and the γ-glutamyl cycle in the absorption of amino acids, noting differences in energy requirements and capacity.",
            a: "<strong>Carrier Protein System:</strong><br><em>Mechanism:</em> Na⁺-dependent cotransporters; 1 ATP per amino acid; high specificity and energy‑efficient for routine absorption.<br><strong>γ‑Glutamyl Cycle:</strong><br><em>Mechanism:</em> Glutathione-mediated amino acid binding and transfer; high capacity, rapid uptake under high loads; energy‑demanding due to glutathione regeneration."
          },
          {
            q: "5. Summarize the metabolic fates of absorbed carbohydrates, lipids, and proteins after digestion, highlighting how each macronutrient contributes to energy production, storage, or biosynthesis.",
            a: "<strong>Carbohydrates:</strong><br><em>Fates:</em> Glycolysis → ATP; glycogenesis in liver/muscle; lipogenesis when in excess.<br><strong>Lipids:</strong><br><em>Fates:</em> β‑oxidation → acetyl‑CoA → Krebs; re‑esterified into triglycerides for adipose storage; precursor for steroid hormones.<br><strong>Proteins:</strong><br><em>Fates:</em> Amino acids used for protein synthesis; deaminated residues → gluconeogenesis or Krebs intermediates; nitrogen → urea cycle."
          }
        ]
    },
     // LECTURE 6: Biochemistry
    {
       id: 'l6',
       name: 'L6 Biochemistry',
       mcqs: [
         { q: "1. Which statement best defines glycolysis?", o: ["A metabolic pathway in the mitochondria that synthesizes glucose from pyruvate.", "The breakdown of lipids into fatty acids in the cytosol.", "A series of cytosolic reactions that break down glucose into two pyruvate molecules.", "The conversion of pyruvate into lactate exclusively.", "A process that exclusively produces glycogen from glucose."], a: "c) A series of cytosolic reactions that break down glucose into two pyruvate molecules." },
         { q: "2. Which enzyme catalyzes the first irreversible reaction in glycolysis?", o: ["Phosphofructokinase-1 (PFK-1)", "Pyruvate kinase", "Aldolase", "Hexokinase/Glucokinase", "Enolase"], a: "d) Hexokinase/Glucokinase" },
         { q: "3. During the energy investment phase of glycolysis, how many ATP molecules are consumed per molecule of glucose?", o: ["1 ATP", "2 ATP", "3 ATP", "4 ATP", "0 ATP"], a: "b) 2 ATP" },
         { q: "4. What are the net products of glycolysis from one molecule of glucose?", o: ["2 pyruvate, 4 ATP, 2 NADH", "2 pyruvate, 2 ATP, 2 NADH", "2 lactate, 2 ATP, 2 FADH₂", "2 Acetyl CoA, 2 ATP, 2 NADH", "2 oxaloacetate, 2 GTP, 2 NADPH"], a: "b) 2 pyruvate, 2 ATP, 2 NADH" },
         { q: "5. Under anaerobic conditions, which enzyme converts pyruvate to lactate?", o: ["Hexokinase", "Phosphofructokinase-1", "Pyruvate dehydrogenase", "Lactate dehydrogenase", "Pyruvate kinase"], a: "d) Lactate dehydrogenase" },
         { q: "6. In aerobic glycolysis, what is the fate of NADH generated during the pathway?", o: ["It is converted to NADPH in the pentose phosphate pathway.", "It directly phosphorylates ADP to ATP in the cytosol.", "It enters the electron transport chain to yield approximately 3 ATP per NADH.", "It is used to convert lactate to pyruvate.", "It is degraded in the Krebs cycle."], a: "c) It enters the electron transport chain to yield approximately 3 ATP per NADH." },
         { q: "7. Which set of enzymes represents the key rate-limiting steps in glycolysis?", o: ["Aldolase, enolase, and triose phosphate isomerase", "Hexokinase/Glucokinase, Phosphofructokinase-1 (PFK-1), and Pyruvate kinase", "Phosphoglycerate kinase, Glyceraldehyde-3-phosphate dehydrogenase, and enolase", "Glucose-6-phosphatase, lactate dehydrogenase, and pyruvate kinase", "Pyruvate dehydrogenase, citrate synthase, and isocitrate dehydrogenase"], a: "b) Hexokinase/Glucokinase, Phosphofructokinase-1 (PFK-1), and Pyruvate kinase" },
         { q: "8. Where in the cell does glycolysis occur?", o: ["Mitochondrial matrix", "Cytosol", "Endoplasmic reticulum", "Nucleus", "Golgi apparatus"], a: "b) Cytosol" },
         { q: "9. Under aerobic conditions, which enzyme complex catalyzes the conversion of pyruvate to Acetyl CoA?", o: ["Citrate synthase complex", "Pyruvate dehydrogenase complex", "α-Ketoglutarate dehydrogenase complex", "Succinate dehydrogenase complex", "Fumarase complex"], a: "b) Pyruvate dehydrogenase complex" },
         { q: "10. What are the products generated from the oxidative decarboxylation of one pyruvate molecule?", o: ["1 Acetyl CoA, 1 CO₂, and 1 NADH", "1 Acetyl CoA, 1 H₂O, and 1 ATP", "2 Acetyl CoA, 2 CO₂, and 2 FADH₂", "1 lactate, 1 CO₂, and 1 NADPH", "2 pyruvate, 1 CO₂, and 1 NADH"], a: "a) 1 Acetyl CoA, 1 CO₂, and 1 NADH" },
         { q: "11. Which of the following coenzymes is NOT directly used in the oxidative decarboxylation of pyruvate?", o: ["Thiamine pyrophosphate (TPP)", "Lipoic acid", "Coenzyme A (CoA-SH)", "NAD⁺", "Coenzyme Q"], a: "e) Coenzyme Q" },
         { q: "12. How many molecules of NADH are produced from the oxidation of one molecule of pyruvate?", o: ["0", "1", "2", "3", "4"], a: "b) 1" },
         { q: "13. Which enzyme catalyzes the first step of the Krebs cycle by condensing Acetyl CoA with oxaloacetate?", o: ["Isocitrate dehydrogenase", "α-Ketoglutarate dehydrogenase", "Citrate synthase", "Succinate dehydrogenase", "Malate dehydrogenase"], a: "c) Citrate synthase" },
         { q: "14. Which of the following enzymes is not a component of the Krebs cycle?", o: ["Citrate synthase", "Isocitrate dehydrogenase", "Pyruvate kinase", "α-Ketoglutarate dehydrogenase", "Succinate dehydrogenase"], a: "c) Pyruvate kinase" },
         { q: "15. Per turn of the Krebs cycle (per Acetyl CoA), how many molecules of NADH are produced?", o: ["1", "2", "3", "4", "0"], a: "c) 3" },
         { q: "16. Which set of products is generated by one molecule of Acetyl CoA entering the Krebs cycle?", o: ["1 CO₂, 1 ATP, 2 NADH, and 1 FADH₂", "2 CO₂, 1 ATP, 3 NADH, and 1 FADH₂", "2 CO₂, 2 ATP, 2 NADH, and 2 FADH₂", "1 CO₂, 2 ATP, 3 NADH, and 0 FADH₂", "2 CO₂, 1 ATP, 1 NADH, and 3 FADH₂"], a: "b) 2 CO₂, 1 ATP, 3 NADH, and 1 FADH₂" },
         { q: "17. Which of the following enzymes is allosterically inhibited by high ATP and NADH levels in the Krebs cycle?", o: ["Malate dehydrogenase", "Citrate synthase", "Aconitase", "Succinate dehydrogenase", "Fumarase"], a: "b) Citrate synthase" },
         { q: "18. The conversion of α-ketoglutarate to succinyl CoA in the Krebs cycle is catalyzed by which enzyme?", o: ["Isocitrate dehydrogenase", "Pyruvate dehydrogenase", "α-Ketoglutarate dehydrogenase", "Citrate synthase", "Malate dehydrogenase"], a: "c) α-Ketoglutarate dehydrogenase" },
         { q: "19. What is the immediate net ATP (or GTP) yield produced directly by one complete turn of the Krebs cycle from Acetyl CoA?", o: ["4 ATP", "3 ATP", "2 ATP", "1 ATP", "0 ATP"], a: "d) 1 ATP" },
         { q: "20. What is the total net ATP yield, including oxidative phosphorylation, produced from one complete turn of the Krebs cycle from Acetyl CoA?", o: ["1 ATP", "2 ATP", "9 ATP", "10 ATP", "12 ATP"], a: "e) 12 ATP" }
       ],
       written: [
        {
          q: "1. Compare and contrast aerobic and anaerobic glycolysis in terms of end products and energy yield.",
          a: "<strong>Aerobic Glycolysis:</strong><br><em>End Products:</em> Pyruvate → acetyl‑CoA → Krebs cycle → CO₂/H₂O.<br><em>Yield:</em> Net 2 ATP + NADH per glucose (NADH → ~2.5 ATP via ETC).<br><strong>Anaerobic Glycolysis:</strong><br><em>End Products:</em> Pyruvate → lactate.<br><em>Yield:</em> Net 2 ATP per glucose; regenerates NAD⁺ for continued glycolysis."
        },
        {
          q: "2. Explain the role of key regulatory enzymes in glycolysis and describe how cellular energy status affects their activity.",
          a: "<strong>Hexokinase/Glucokinase:</strong><br><em>Regulation:</em> Inhibited by G6P (hexokinase) or modulated by insulin/glucagon (glucokinase).<br><strong>Phosphofructokinase‑1 (PFK‑1):</strong><br><em>Allosteric:</em> Inhibited by ATP and citrate; activated by AMP and fructose‑2,6‑bisphosphate.<br><strong>Pyruvate Kinase:</strong><br><em>Regulation:</em> Inhibited by ATP and alanine; activated by fructose‑1,6‑bisphosphate."
        },
        {
          q: "3. Describe the process and significance of the oxidative decarboxylation of pyruvate.",
          a: "<strong>Pyruvate Dehydrogenase Complex:</strong><br><em>Cofactors:</em> Thiamine pyrophosphate (TPP), lipoate, FAD, NAD⁺, CoA‑SH.<br><em>Process:</em> Decarboxylation of pyruvate → hydroxyethyl‑TPP → acetyl‑lipoate → acetyl‑CoA + NADH + CO₂.<br><strong>Significance:</strong> Links cytosolic glycolysis to mitochondrial Krebs cycle, a key control point for aerobic metabolism."
        },
        {
          q: "4. Outline the major steps of the Krebs cycle and summarize the energy carriers generated in one turn per Acetyl CoA molecule.",
          a: "<strong>Major Steps:</strong><br>– Acetyl‑CoA + oxaloacetate → citrate<br>– Citrate → isocitrate → α‑ketoglutarate → succinyl‑CoA → succinate → fumarate → malate → oxaloacetate.<br><strong>Energy Carriers:</strong> 3 NADH, 1 FADH₂, 1 GTP (ATP equivalent), and 2 CO₂ released."
        },
        {
          q: "5. Discuss the physiological importance of glucose oxidation in cellular metabolism.",
          a: "<strong>ATP Production:</strong> Primary source of cellular energy via glycolysis, Krebs, and ETC.<br><strong>Metabolic Flexibility:</strong> Provides intermediates for amino acid and lipid biosynthesis.<br><strong>Redox Balance:</strong> NADH/FADH₂ generation drives oxidative phosphorylation; supports high‑demand tissues (brain, muscle)."
        }
      ]
    },
       // LECTURE 7: Physiology
    {
      id: 'l7',
      name: 'L7 Physiology',
      mcqs: [
        { q: "1. Which of the following best defines mastication?", o: ["The chemical digestion of food solely by enzymes in saliva.", "The process of grinding food into smaller particles to facilitate swallowing.", "The transport of food from the mouth to the stomach via peristalsis.", "The reflex inhibition of jaw muscles during food compression.", "The secretion of mucus by salivary glands."], a: "b) The process of grinding food into smaller particles to facilitate swallowing." },
        { q: "2. Which structures are primarily involved in mastication?", o: ["Mandible, lips, cheeks, and tongue.", "Epiglottis, soft palate, and larynx.", "Esophagus, stomach, and LES.", "Vocal cords and pharyngeal constrictor muscles.", "Trachea, bronchi, and alveoli."], a: "a) Mandible, lips, cheeks, and tongue." },
        { q: "3. What is the role of the chewing (mastication) reflex?", o: ["It initiates the voluntary swallowing of the bolus.", "It continuously coordinates jaw movement by providing a stretch-induced rebound contraction.", "It directly stimulates salivary enzyme secretion independent of mastication.", "It closes the upper esophageal sphincter during swallowing.", "It inhibits the movements of the tongue during food mixing."], a: "b) It continuously coordinates jaw movement by providing a stretch-induced rebound contraction." },
        { q: "4. Which neural structure is involved as the afferent limb of the chewing reflex?", o: ["Spinal trigeminal nucleus", "Mesencephalic nucleus of the trigeminal nerve", "Motor nucleus of the facial nerve", "Nucleus ambiguus", "Dorsal motor nucleus of the vagus"], a: "b) Mesencephalic nucleus of the trigeminal nerve" },
        { q: "5. How does mastication facilitate subsequent digestive processes?", o: ["By solely initiating chemical digestion without mechanical breakdown.", "By decreasing the surface area of food particles exposed to enzymes.", "By stimulating salivary secretion, mixing with food, and increasing surface area.", "By completely digesting food before it reaches the stomach.", "By directly activating esophageal peristalsis."], a: "c) By stimulating salivary secretion, mixing with food, and increasing surface area." },
        { q: "6. Which phase of swallowing is under voluntary control?", o: ["Esophageal phase", "Pharyngeal phase", "Buccal (oral) phase", "Involuntary reflex phase", "Gastroesophageal phase"], a: "c) Buccal (oral) phase" },
        { q: "7. During the buccal phase of swallowing, what mechanism is primarily responsible for initiating the movement of the bolus into the pharynx?", o: ["Downward movement of the soft palate", "Upward and backward movement of the tongue against the palate", "Contraction of the esophageal musculature", "Closure of the vocal cords", "Relaxation of the upper esophageal sphincter"], a: "b) Upward and backward movement of the tongue against the palate" },
        { q: "8. Which of the following events does NOT occur during the pharyngeal phase of swallowing?", o: ["Elevation of the soft palate to block the nasal cavity", "Approximation of the palatopharyngeal folds", "Active contraction of the esophageal musculature to propel the bolus", "Downward retraction and re-closing of the upper esophageal sphincter", "Upward and anterior displacement of the larynx"], a: "c) Active contraction of the esophageal musculature to propel the bolus" },
        { q: "9. What is the primary function of the soft palate during swallowing?", o: ["To initiate esophageal peristalsis.", "To block the nasal cavity from the bolus passage.", "To close the laryngeal inlet.", "To contract the upper esophageal sphincter.", "To regulate vocal cord positioning."], a: "b) To block the nasal cavity from the bolus passage." },
        { q: "10. Which nerves serve as the afferent pathways that trigger the swallowing reflex?", o: ["Optic, auditory, and vestibular nerves", "V, VII, and XI cranial nerves", "V, IX, and X cranial nerves", "V, X, and XII cranial nerves", "III, IV, and VI cranial nerves"], a: "c) V, IX, and X cranial nerves" },
        { q: "11. During the pharyngeal phase, which combination of nerves contributes to the efferent signals for swallowing?", o: ["V, VII, IX, and X", "V, IX, X, and XII", "V, VI, XI, and XII", "VII, IX, X, and XI", "V, III, X, and XII"], a: "b) V, IX, X, and XII" },
        { q: "12. What is the significance of the upward and anterior movement of the larynx during swallowing?", o: ["It dilates the esophageal sphincters for rapid food passage.", "It stimulates secondary peristalsis in the esophagus.", "It ensures that the epiglottis covers the laryngeal inlet, reducing the risk of aspiration.", "It actively contracts the pharyngeal constrictor muscles to break down the bolus.", "It increases the rate of saliva secretion."], a: "c) It ensures that the epiglottis covers the laryngeal inlet, reducing the risk of aspiration." },
        { q: "13. Which statement best summarizes the relative importance of the epiglottis and vocal cords during swallowing?", o: ["The epiglottis is critical for airway protection, while the vocal cords play a minor role.", "Both structures are equally non-essential as long as the larynx is elevated.", "Vocal cord approximation and laryngeal elevation are essential, whereas the epiglottis, if absent, presents less danger.", "Neither structure is important for preventing aspiration.", "Vocal cords remain open during swallowing while the epiglottis closes."], a: "c) Vocal cord approximation and laryngeal elevation are essential, whereas the epiglottis, if absent, presents less danger." },
        { q: "14. What best describes swallowing apnea?", o: ["A reflex contraction of the upper esophageal sphincter during food bolus transit.", "A temporary cessation of respiration triggered by the swallowing center.", "A rhythmic oscillation of laryngeal muscles during the pharyngeal phase.", "An involuntary spasm of the vocal cords after swallowing.", "A delayed relaxation of the lower esophageal sphincter."], a: "b) A temporary cessation of respiration triggered by the swallowing center." },
        { q: "15. Which phase of swallowing is characterized by the rapid peristaltic movement that transports the bolus from the pharynx to the stomach?", o: ["Buccal phase", "Pharyngeal phase", "Esophageal phase", "Oral phase", "Gastroesophageal phase"], a: "c) Esophageal phase" },
        { q: "16. Which type of peristalsis is responsible for the primary movement of food in a normally functioning esophagus?", o: ["Tertiary peristalsis", "Secondary peristalsis", "Primary peristalsis initiated by vagal fibers", "Reflex peristalsis mediated by the sympathetic system", "Spontaneous peristalsis independent of neural control"], a: "c) Primary peristalsis initiated by vagal fibers" },
        { q: "17. What triggers secondary peristalsis in the esophagus?", o: ["Voluntary swallowing commands from the cerebral cortex", "Afferent signals from the nucleus ambiguus", "Residual food remaining in the esophagus due to incomplete primary peristalsis", "Direct stimulation of the esophageal smooth muscle by gastrin", "Increased vagal tone during sleeping states"], a: "c) Residual food remaining in the esophagus due to incomplete primary peristalsis" },
        { q: "18. Which statement correctly describes the muscular composition of the esophagus?", o: ["It is entirely composed of smooth muscle fibers.", "The upper third contains smooth muscle, while the lower third is solely striated.", "The esophagus is divided into three parts: the upper third with striated muscle, the middle third with mixed muscle types, and the lower third with smooth muscle.", "It is composed exclusively of striated muscle fibers.", "The muscular composition is uniform along its entire length."], a: "c) The esophagus is divided into three parts: the upper third with striated muscle, the middle third with mixed muscle types, and the lower third with smooth muscle." },
        { q: "19. Which sphincter is considered a true sphincter with tonic contraction at rest?", o: ["Lower esophageal sphincter (LES)", "Pyloric sphincter", "Upper esophageal sphincter (UES)", "Ileocecal sphincter", "Cardiac sphincter"], a: "c) Upper esophageal sphincter (UES)" },
        { q: "20. Which of the following factors is known to decrease the tone of the lower esophageal sphincter (LES)?", o: ["High doses of gastrin after meals", "Ingestion of fatty foods, tea, coffee, and chocolate", "Increased intra-abdominal pressure due to obesity", "Direct stimulation by acetylcholine", "Excessive vagal stimulation leading to increased LES contraction"], a: "b) Ingestion of fatty foods, tea, coffee, and chocolate" }
      ],
      written: [
        {
          q: "1. Discuss the physiological significance of mastication in digestion.",
          a: "<strong>Mechanical Fragmentation:</strong> Breaks food into smaller particles, increasing surface area for enzymes.<br><strong>Salivary Mixing:</strong> Stimulates secretion of saliva containing amylase and lipase.<br><strong>Neural Feedback:</strong> Periodontal mechanoreceptors modulate bite force; enhances taste and prepares swallowing reflex."
        },
        {
          q: "2. Outline the sequential events during the pharyngeal phase of swallowing and explain their functional importance.",
          a: "<strong>Soft Palate Elevation:</strong> Closes nasopharynx to prevent regurgitation.<br><strong>Palatopharyngeal Fold Approximation:</strong> Guides bolus into oropharynx.<br><strong>Laryngeal Elevation & Closure:</strong> Hyoid and larynx move upward/anteriorly; vocal cords adduct; epiglottis covers inlet, protecting airway.<br><strong>Pharyngeal Constrictors:</strong> Sequential contraction propels bolus toward esophagus."
        },
        {
          q: "3. Describe the mechanism by which the swallowing reflex coordinates airway protection during deglutition.",
          a: "<strong>Initiation:</strong> Sensory receptors in oropharynx (CN V, IX, X) send afferents to the swallowing center in the medulla.<br><strong>Motor Output:</strong> Vagal and glossopharyngeal efferents coordinate muscle groups for laryngeal elevation, vocal cord closure, and epiglottic tilt.<br><strong>Central Pattern Generator:</strong> Ensures rapid, sequenced muscle activation to prevent aspiration."
        },
        {
          q: "4. Differentiate between primary and secondary peristalsis in the esophagus.",
          a: "<strong>Primary Peristalsis:</strong> Initiated by voluntary swallow; wave of smooth muscle contraction mediated by myenteric plexus.<br><strong>Secondary Peristalsis:</strong> Reflex response to residual distension; clears remaining bolus without cortical input."
        },
        {
          q: "5. Explain the role and regulatory influences on the lower esophageal sphincter (LES) in preventing gastroesophageal reflux.",
          a: "<strong>LES Tone:</strong> Maintains tonic contraction via smooth muscle tone and myenteric plexus.<br><strong>Decreasing Factors:</strong> Transient LES relaxations, fatty foods, chocolate, caffeine, alcohol, nitric oxide.<br><strong>Increasing Factors:</strong> Gastrin, motilin, cholinergic stimulation; maintains barrier to reflux."
        }
      ]
    },
  
    // LECTURE 8: Pathology
    {
      id: 'l8',
      name: 'L8 Pathology',
      mcqs: [
        { q: "1. A 45-year-old man presents with a 4-cm, firm, movable mass at the angle of the left jaw. Biopsy shows myoepithelial cells with myxoid, mucoid, and cartilaginous areas. What is the most likely prognosis?", o: ["Contralateral spread", "Invasion of bone", "Local recurrence", "Malignant transformation", "Pyogenic abscess"], a: "c) Local recurrence" },
        { q: "2. Which deficiency is most commonly associated with noninfective cheilitis?", o: ["Vitamin C deficiency", "Vitamin D deficiency", "Vitamin B and iron deficiency", "Calcium deficiency", "Folic acid deficiency"], a: "c) Vitamin B and iron deficiency" },
        { q: "3. In cases of aphthous stomatitis, the recurrent painful ulcers are most often related to:", o: ["Bacterial infection", "Mechanical trauma", "Food allergies or viral infections", "Excessive vitamin supplementation", "Autoimmune destruction"], a: "c) Food allergies or viral infections" },
        { q: "4. Which organism is most commonly implicated in the fungal inflammation of the mouth (thrush or candidiasis)?", o: ["Streptococcus pyogenes", "Candida albicans", "Herpes simplex virus", "Staphylococcus aureus", "Epstein-Barr virus"], a: "b) Candida albicans" },
        { q: "5. Atrophic glossitis, affecting the tongue, is commonly associated with which nutritional deficiency?", o: ["Vitamin A deficiency", "Vitamin B12 and iron deficiency", "Vitamin E deficiency", "Protein deficiency", "Calcium deficiency"], a: "b) Vitamin B12 and iron deficiency" },
        { q: "6. Which type of tongue ulcer is typically described as having an undermined edge and a caseous floor, particularly at the tip of the tongue in patients with pulmonary tuberculosis?", o: ["Dental (traumatic) ulcer", "Dyspeptic ulcer", "Tuberculous ulcer", "Syphilitic ulcer", "Malignant ulcer"], a: "c) Tuberculous ulcer" },
        { q: "7. A malignant ulcer on the tongue is most commonly found on which location?", o: ["Dorsum of the tongue", "Tip of the tongue", "Anterior two-thirds, lateral edge", "Base of the tongue", "Ventral surface"], a: "c) Anterior two-thirds, lateral edge" },
        { q: "8. The primary predisposing factors for squamous cell carcinoma of the oral cavity include all EXCEPT:", o: ["Chronic smoking", "Alcohol use", "Mechanical irritation", "Oncogenic viruses", "Excessive dietary fiber"], a: "e) Excessive dietary fiber" },
        { q: "9. Which of the following conditions is considered a precancerous lesion in the oral cavity?", o: ["Squamous cell papilloma", "Leukoplakia", "Hemangioma", "Lymphangioma", "Granular cell tumor"], a: "b) Leukoplakia" },
        { q: "10. In squamous cell carcinoma of the tongue, which site is most commonly affected?", o: ["Posterior one-third", "Central dorsal surface", "Lateral edge of the anterior two-thirds", "Ventral surface", "Tip of the tongue"], a: "c) Lateral edge of the anterior two-thirds" },
        { q: "11. Which of the following is a common complication associated with mumps-related sialadenitis?", o: ["Local recurrence", "Pulmonary embolism", "Orchitis", "Bone invasion", "Fibrosis of the parotid gland"], a: "c) Orchitis" },
        { q: "12. The formation of salivary gland duct stones (sialolithiasis) typically begins with which of the following processes?", o: ["Direct bacterial infection of the gland", "Deposition of calcium around food debris or desquamated cells", "Autoimmune destruction of acini", "Neoplastic transformation of ductal cells", "Vascular calcification of glandular tissue"], a: "b) Deposition of calcium around food debris or desquamated cells" },
        { q: "13. Which benign salivary gland tumor is described as the \"pleomorphic adenoma\" characterized by a well-demarcated, rounded mass with tongue-like projections and a mix of epithelial and myoepithelial components?", o: ["Papillary cystadenoma lymphomatosum", "Oncocytoma", "Pleomorphic adenoma", "Warthin's tumor", "Acinic adenocarcinoma"], a: "c) Pleomorphic adenoma" },
        { q: "14. Warthin's tumor, also known as papillary cystadenoma lymphomatosum, commonly occurs in which demographic?", o: ["Young females", "Middle-aged females", "Old males", "Pediatric patients", "Adolescents"], a: "c) Old males" },
        { q: "15. Oncocytoma of the salivary gland typically demonstrates which of the following histological features?", o: ["Cystic spaces with papillary ingrowth", "Sheets of large cells with abundant red granular cytoplasm and a hyalinized stroma", "Mixed epithelial and myoepithelial components with cartilaginous areas", "Predominant lymphoid infiltration with germinal centers", "Focal necrosis and hemorrhage on cut section"], a: "b) Sheets of large cells with abundant red granular cytoplasm and a hyalinized stroma" },
        { q: "16. Among malignant salivary gland tumors, which one is characterized by a dual cell population with mucus-secreting and squamous components?", o: ["Acinic adenocarcinoma", "Mucoepidermoid carcinoma", "Adenoid cystic carcinoma", "Malignant mixed tumor", "Squamous cell carcinoma"], a: "b) Mucoepidermoid carcinoma" },
        { q: "17. Which of the following is a noted feature indicating malignant transformation in pleomorphic adenoma?", o: ["Slow rate of growth and soft consistency", "Complete encapsulation with no projections", "Rapid rate of growth, facial nerve paralysis, and hard, fixed consistency", "Cystic architecture with mucinous secretion", "Presence of lymphoid aggregates in the stroma"], a: "c) Rapid rate of growth, facial nerve paralysis, and hard, fixed consistency" },
        { q: "18. Which salivary gland tumor is most commonly found in the parotid gland and has a high recurrence rate due to its incomplete capsule?", o: ["Oncocytoma", "Pleomorphic adenoma", "Warthin's tumor", "Adenoid cystic carcinoma", "Squamous cell carcinoma"], a: "b) Pleomorphic adenoma" },
        { q: "19. Regarding malignant salivary gland tumors, which factor does NOT typically contribute to the cause of death?", o: ["Aspiration bronchopneumonia", "Hemorrhage", "Cachexia", "Local recurrence", "Metastatic spread to the lungs"], a: "d) Local recurrence" },
        { q: "20. Which of the following neoplastic lesions is most closely associated with chronic irritation from smoking or mechanical trauma in the oral cavity?", o: ["Lymphangioma", "Squamous cell carcinoma", "Hemangioma", "Granular cell tumor", "Oncocytoma"], a: "b) Squamous cell carcinoma" }
      ],
      written: [
        {
          q: "1. Explain the pathogenic mechanism underlying aphthous stomatitis and describe its typical clinical features.",
          a: "<strong>Pathogenesis:</strong> T‑cell mediated immune response causing epithelial ulceration on non‑keratinized mucosa; triggers include stress, nutritional deficiencies, and viral infections.<br><strong>Clinical Features:</strong> Small round/oval ulcers with erythematous halo and yellow‑grey pseudomembrane; painful, recurrent, heal without scarring in 7–14 days."
        },
        {
          q: "2. Describe the clinical and pathological differences between traumatic (dental) ulcers and malignant ulcers of the tongue.",
          a: "<strong>Traumatic Ulcers:</strong> Shallow, irregular margins, adjacent to sharp tooth edges; heal after removing irritant; minimal induration.<br><strong>Malignant Ulcers:</strong> Persistent, with raised, everted margins; necrotic base; firm, fixed indurated surrounding tissue; require biopsy to rule out squamous cell carcinoma."
        },
        {
          q: "3. Outline the etiopathogenesis of mumps-related sialadenitis, including its typical histopathological findings and potential complications.",
          a: "<strong>Etiology:</strong> Paramyxovirus transmitted by respiratory droplets.<br><strong>Histopathology:</strong> Diffuse interstitial inflammation with plasma cell and lymphocytic infiltrates; acinar cell destruction.<br><strong>Complications:</strong> Orchitis, oophoritis, pancreatitis, aseptic meningitis, hearing loss."
        },
        {
          q: "4. Compare and contrast the histopathologic features and clinical behavior of pleomorphic adenoma and Warthin’s tumor in salivary glands.",
          a: "<strong>Pleomorphic Adenoma:</strong> Mixed epithelial and myoepithelial cells in mucoid, myxoid, or chondroid stroma; locally infiltrative, high recurrence if not completely excised; potential malignant transformation.<br><strong>Warthin’s Tumor:</strong> Papillary cystic spaces lined by double layer of oncocytic cells with lymphoid stroma; almost exclusively parotid, elderly males; benign, rare recurrence, no malignant change."
        },
        {
          q: "5. Discuss the role of chronic irritation and precancerous lesions in the development of squamous cell carcinoma of the oral cavity.",
          a: "<strong>Chronic Irritants:</strong> Tobacco, alcohol, mechanical trauma induce DNA damage.<br><strong>Precancerous Lesions:</strong> Leukoplakia, erythroplakia, lichen planus exhibit dysplasia.<br><strong>Progression:</strong> Accumulation of mutations (e.g., p53) leads to invasive squamous cell carcinoma, commonly on lateral tongue and floor of mouth."
        }
      ]
    },
];
